OnlineShopCMS/OnlineShopCMS/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShopCMS.Data;
using OnlineShopCMS.Models;

namespace OnlineShopCMS.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ProductsController : Controller
    {
        private readonly OnlineShopContext _context;

        public ProductsController(OnlineShopContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            var result = from m in _context.Product select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                result = result.Where(s => s.Name.Contains(searchString));
            }
<<<<<<< HEAD
            var userName = User.Identity.Name;
            ViewData["UserName"] = userName;
=======

>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
            int pageSize = 5;
            return View(await PaginatedList<Product>.CreateAsync(result.Include(p => p.Category).AsNoTracking(), pageNumber ?? 1, pageSize));
        }

<<<<<<< HEAD
        // GET: Products/Details/
        public async Task<IActionResult> Details(int? id)
        {
=======
        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            DetailViewModel dvm = new DetailViewModel();

>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
            if (id == null)
            {
                return NotFound();
            }

<<<<<<< HEAD
            DetailViewModel dvm = new DetailViewModel();  

            var product = await _context.Product
                        .Include(p => p.Category)
                        .FirstOrDefaultAsync(m => m.Id == id);
=======
            var product = await _context.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
            if (product == null)
            {
                return NotFound();
            }
            else
            {
                dvm.product = product;
                if (product.Image != null)
                {
                    dvm.imgsrc = ViewImage(product.Image);
                }
            }
<<<<<<< HEAD
            return View(dvm); 
        }
=======

            return View(dvm);
        }

>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["Categories"] = new SelectList(_context.Set<Category>(), "Id", "Name");
            return View();
        }

<<<<<<< HEAD
       
=======
        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Content,Price,Stock,Image,CategoryId")] Product product, IFormFile myimg)
        {
            if (ModelState.IsValid)
            {
                if (myimg != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        myimg.CopyTo(ms);
                        product.Image = ms.ToArray();
                    }
                }
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Categories"] = new SelectList(
                _context.Set<Category>(), "Id", "Name", product.CategoryId);
            return View(product);
        }

<<<<<<< HEAD
        // GET: Products/EditOrder/5
=======
        // GET: Products/Edit/5
>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            else
            {
                if (product.Image != null)
                {
                    ViewBag.Image = ViewImage(product.Image);
                }
            }
            ViewData["Categories"] = new SelectList(_context.Set<Category>(), "Id", "Name", product.CategoryId); //設定seleccted項目

            return View(product);
        }

<<<<<<< HEAD
      
=======
        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Content,Price,Stock,Image,CategoryId")] Product product, IFormFile myimg)
        {
<<<<<<< HEAD
            var prod = new Product();

=======
>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
<<<<<<< HEAD
=======
                    var productToUpdate = await _context.Product.FindAsync(id);

>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
                    if (myimg != null)
                    {
                        using (var ms = new MemoryStream())
                        {
                            myimg.CopyTo(ms);
<<<<<<< HEAD
                            product.Image = ms.ToArray();
                        }
                    }
                    _context.Update(product);
=======
                            productToUpdate.Image = ms.ToArray();
                        }
                    }

                    productToUpdate.Name = product.Name;
                    productToUpdate.Description = product.Description;
                    productToUpdate.Content = product.Content;
                    productToUpdate.Price = product.Price;
                    productToUpdate.Stock = product.Stock;
                    productToUpdate.CategoryId = product.CategoryId;

                    _context.Update(productToUpdate);
>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

<<<<<<< HEAD
            var product = await _context.Product.FindAsync(id);
=======
            var product = await _context.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
            if (product == null)
            {
                return NotFound();
            }

<<<<<<< HEAD
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product
                .Include(p => p.Comments) // 確保載入評論
                .FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            // 刪除所有相關的評論
            _context.Comment.RemoveRange(product.Comments);
            await _context.SaveChangesAsync();

            // 現在刪除產品
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }





=======
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

>>>>>>> 6c1fd4ee0d5dbde6c6b3ed2f1e2922a5860308c0
        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategory(Category category)
        {
            _context.Category.Add(category);
            await _context.SaveChangesAsync();
            return View();
        }

<<<<<<< HEAD
        public async Task<IActionResult> ListCategories(int? id)
        {
            var categories = await _context.Category.ToListAsync();
            return View(categories);

        }

OnlineShopCMS/OnlineShopCMS/Controllers/PromotionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using OnlineShopCMS.Areas.Identity.Data;
using OnlineShopCMS.Data;
using OnlineShopCMS.Models;
using OnlineShopCMS.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using static Microsoft.AspNetCore.Razor.Language.TagHelperMetadata;


namespace OnlineShopCMS.Controllers
{
    // TODO: 完成 PromotionController
    [Authorize(Roles = "Administrator")]
    public class PromotionController : Controller
    {
        private readonly IConfiguration _config;
        private readonly IPromotionService _promotionService;
        private readonly OnlineShopContext _context;
        private readonly UserManager<OnlineShopUser> _userManager;



        public PromotionController(IPromotionService promotionService, OnlineShopContext context, UserManager<OnlineShopUser> userManager, IConfiguration config)
        {
            _promotionService = promotionService;
            _context = context;
            _userManager = userManager;
            _config = config;
        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            // 從服務層中獲取所有促銷活動
            var promotions = _promotionService.GetAllPromotions().ToList();
            ViewBag.Products = _context.Product.ToList();

            // 進行對促銷活動屬性的處理
            foreach (var promotion in promotions)
            {
                if (promotion.DiscountType != null)
                {
                    // 對 DiscountType 不為空的情況進行處理
                }

                if (promotion.DiscountValue != null)
                {
                    // 對 DiscountValue 不為空的情況進行處理
                }

                // 其他屬性的處理方式類似
            }

            // 將處理過的促銷活動列表傳遞給視圖
            return View(promotions);
        }

        [HttpGet]
        public IActionResult ListCoupon()
        {
            var coupons = _context.Coupon.ToList();
            return View(coupons);
        }

        [HttpGet]
        public IActionResult ListPromotions()
        {
            var coupons = _context.Coupon.ToList();
            return View(coupons);
        }




        public async Task<IActionResult> EditCoupon(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _context.Coupon.FindAsync(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }


        // GET: Coupons/Create
        public IActionResult CreateCoupon()
        {
            return View();
        }

        // POST: Coupons/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCoupon([Bind("Id,Code,DiscountAmount,ExpiryDate")] Coupon coupon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(coupon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }
        // GET: Promotion/Create
        public IActionResult Create()
        {
            var products = _context.Product.ToList();
            if (!products.Any())
            {
              
                TempData["Error"] = "No products available. Please add products before creating promotions.";
                return RedirectToAction("Index");
            }

            ViewBag.Products = products;
            return View(new Promotion());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Promotion promotion)
        {
            var products = _context.Product.ToList();
            ViewBag.Products = products;

            if (!products.Any())
            {
                TempData["Error"] = "No products available. Please add products before creating promotions.";
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                _context.Promotions.Add(promotion);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(promotion);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotions.FindAsync(id);
            if (promotion == null)
            {
                return NotFound();
            }
            return View(promotion);
        }

        // POST: Promotion/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Code,StartDate,EndDate,IsActive")] Promotion promotion)
        {
            if (id != promotion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                    var existingPromotion = await _context.Promotions.FindAsync(id);
                    if (existingPromotion == null)
                    {
                        return NotFound();
                    }

                   
                    existingPromotion.Name = promotion.Name;
                    existingPromotion.Description = promotion.Description;
                    existingPromotion.Code = promotion.Code;
                    existingPromotion.StartDate = promotion.StartDate;
                    existingPromotion.EndDate = promotion.EndDate;
                    existingPromotion.IsActive = promotion.IsActive;

                   
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromotionExists(promotion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(promotion);
        }




        private bool PromotionExists(int id)
        {
            return _context.Promotions.Any(e => e.Id == id);
        }


    }
}

OnlineShopCMS/OnlineShopCMS/Views/Shared/_PromotionManagLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using OnlineShopCMS.Areas.Identity.Data
@inject SignInManager<OnlineShopUser> SignInManager
@inject UserManager<OnlineShopUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin Pro</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-XXX" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/fontawesome-free-5.15.4-web/css/all.css" />



    <link href="@Url.Content("~/css/styles.css")" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/assets/img/favicon.png")" />
    <script data-search-pseudo-elements defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.29.0/feather.min.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e8d28c4e09.js" crossorigin="anonymous"></script>

    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" />
</head>
<body class="nav-fixed">
    <nav class="navbar-items-container topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white" id="sidenavAccordion">
        <style>
            /* site.css */
            .navbar-items-container {
                margin-right: 1rem; /* Or any other appropriate value */
            }

        </style>
        <!-- Sidenav Toggle Button-->
        <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0" id="sidebarToggle"><i data-feather="menu"></i></button>
        <!-- Navbar Brand-->
        <!-- * * Tip * * You can use text or an image for your navbar brand.-->
        <!-- * * * * * * When using an image, we recommend the SVG format.-->
        <!-- * * * * * * Dimensions: Maximum height: 32px, maximum width: 240px-->
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">
            <img src="@Url.Content("~/assets/img/logo5.jpg")" alt="Your Logo" style="width:160px; height:60px;">
        </a>


        <!-- Navbar Search Input-->
        <!-- * * Note: * * Visible only on and above the lg breakpoint-->
        <form class="form-inline me-auto d-none d-lg-block me-3">
            <div class="input-group input-group-joined input-group-solid">
                <input class="form-control pe-0" type="search" placeholder="Search" aria-label="Search" />
                <div class="input-group-text"><i data-feather="search"></i></div>
            </div>
        </form>
        <!-- Navbar Items-->

        <div class="navbar-items-container" style="margin-right: 1rem;">
            <!-- Adjust the margin as needed -->
            <partial name="_LoginPartial" />
        </div>
        <li class="nav-item dropdown no-caret me-3 d-lg-none">
            <a class="btn btn-icon btn-transparent-dark dropdown" id="navbarSearch" data-bs-toggle="dropdown" aria-label="Search"><i data-feather="search"></i></a>
            <!-- Dropdown - Search-->
            <div class="dropdown-menu dropdown-menu-end p-3">
                <form class="form-inline me-auto w-100">
                    <div class="input-group input-group-joined input-group-solid">
                        <input class="form-control pe-0" type="search" placeholder="Search" aria-label="Search" />
                        <div class="input-group-text"><i data-feather="search"></i></div>
                    </div>
                </form>
            </div>


        </li>
    </nav>


    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sidenav shadow-right sidenav-light">
                <div class="sidenav-menu">
                    <script>

                    </script>
                    <div class="nav accordion" id="accordionSidenav">
                        <!-- Sidenav Menu Heading (Core)-->
                        <div class="sidenav-menu-heading">核心</div>
                        <!-- Sidenav Link (Dashboard)-->

                        <a class="nav-link" href="@Url.ActionLink("Dashboard", "Home")">
                            <div class="nav-link-icon"><i data-feather="activity"></i></div>
                            儀表板
                        </a>

                        <!-- Sidenav Menu Heading (Management)-->
                        <div class="sidenav-menu-heading">訂單管理</div>
                        <!-- Sidenav Link (Orders)-->
                        <!-- Sidenav Dropdown (Orders) -->

                        <li><a href="@Url.Action("Index", "Order", new { area = "" })" class="nav-link"><i class="fas fa-list"></i> 訂單列表</a></li>
                        <li><a href="@Url.Action("Index", "Order", new { area = "" })" class="nav-link"><i class="fas fa-chart-line"></i> 我的銷售</a></li>
                        <li><a href="@Url.Action("Index", "Order", new { area = "" })" class="nav-link"><i class="fas fa-truck"></i> 批次出貨</a></li>
                        <li><a href="@Url.Action("FailOrders", "Order", new { area = "" })" class="nav-link"><i class="fas fa-times"></i> 不成立</a></li>
                        <li><a href="@Url.Action("Search", "Order", new { area = "" })" class="nav-link"><i class="fas fa-list"></i> 查詢訂單</a></li>
                        <li><a href="@Url.Action("Index", "Order", new { area = "" })" class="nav-link"><i class="fas fa-undo"></i> 退貨/退款</a></li>
                        <li><a href="@Url.Action("Index", "Order", new { area = "" })" class="nav-link"><i class="fas fa-truck"></i> 物流設定</a></li>

                        <!-- Sidenav Menu Heading (Management)-->
                        <div class="sidenav-menu-heading">產品管理</div>

                        <li><a href="@Url.Action("Index", "Products", new { area = "" })" class="nav-link"><i class="fas fa-list"></i> 產品列表</a></li>
                        <li><a href="@Url.Action("Create", "Products", new { area = "" })" class="nav-link"><i class="fas fa-plus"></i> 產品上架</a></li>
                        <li><a href="@Url.Action("ListCategories", "Products", new { area = "" })" class="nav-link"><i class="fas fa-tags"></i> 產品類別</a></li>
                        <li><a href="@Url.Action("CreateCategory", "Products", new { area = "" })" class="nav-link"><i class="fas fa-tag"></i> 新增產品類別</a></li>

                        <!-- Sidenav Menu Heading (Management)-->
                        <div class="sidenav-menu-heading">使用者管理</div>

                        <li><a href="@Url.Action("ListUsers", "Users", new { area = "" })" class="nav-link"><i class="fas fa-users"></i> 帳戶列表</a></li>
                        <li><a href="@Url.Action("CreateUser", "Users", new { area = "" })" class="nav-link"><i class="fas fa-user-plus"></i> 新增帳戶</a></li>

                        <!-- Sidenav Menu Heading (Management)-->
                        <div class="sidenav-menu-heading">權限管理</div>

                        <li><a href="@Url.Action("ListRoles", "Users", new { area = "" })" class="nav-link"><i class="fas fa-user-cog"></i> 角色/權限列表</a></li>
                        <li><a href="@Url.Action("CreateRole", "Users", new { area = "" })" class="nav-link"><i class="fas fa-cogs"></i> 新增角色及權限</a></li>

                        <li><a href="@Url.Action("Settings", "Home", new { area = "" })" class="nav-link"><i class="fas fa-cog"></i> 設定</a></li>

                        <!-- Sidenav Menu Heading (Management)-->
                        <div class="sidenav-menu-heading">促銷及優惠管理中心</div>

                        <li><a href="@Url.Action("Index", "Promotion", new { area = "" })" class="nav-link"><i class="fas fa-gift"></i> 促銷活動</a></li> 
                        <li><a href="@Url.Action("Create", "Promotion", new { area = "" })" class="nav-link"><i class="fas fa-plus"></i> 新增促銷活動</a></li>









                        <!-- Sidenav Link (Settings)-->
                        <a class="nav-link" href="settings.html">
                            <div class="nav-link-icon"><i data-feather="settings"></i></div>
                            系統設置
                        </a>
                    </div>
                </div>
                <!-- Sidenav Footer-->
                <div class="sidenav-footer">
                    <div class="sidenav-footer-content">
                        <div class="sidenav-footer-subtitle">Logged in as:</div>
                        <div class="sidenav-footer-title">Valerie Luna</div>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
                    <div class="container-xl px-4">
                        <div class="page-header-content pt-4">
                            <div class="row align-items-center justify-content-between">
                                <div class="col-auto mt-4">
                                    <h1 class="page-header-title">
                                        <div class="page-header-icon"><i data-feather="activity"></i></div>
                                        Hello @UserManager.GetUserAsync(User).Result.Name!歡迎來到優惠及促銷活動管理中心
                                    </h1>
                                    <div class="page-header-subtitle">Welcome to the order management center</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </header>
                <!-- Main page content-->
                <div class="container-xl px-4 mt-n10 position-relative">

                    @RenderBody()
                </div>
            </main>
            <footer class="footer-admin mt-auto footer-light">
                <div class="container-xl px-4">
                    <div class="row">
                        <div class="col-md-6 small">Copyright &copy; Your Website 2024</div>
                        <div class="col-md-6 text-md-end small">
                            <a href="#!">Privacy Policy</a>
                            &middot;
                            <a href="#!">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @RenderSection("Scripts", required: false)
    @RenderSection("editScripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/lib/ckeditor5/build/ckeditor.js.map")"></script>

    <script src="@Url.Content("~/lib/ckeditor5/build/ckeditor.js")"></script>
    <script src="@Url.Content("~/js/scripts.js")"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" crossorigin="anonymous"></script>

    <script src="@Url.Content("~/assets/demo/chart-area-demo.js")"></script>
    <script src="@Url.Content("~/assets/demo/chart-pie-demo.js")"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/js/datatables/datatables-simple-demo.js")"></script>
</body>

</html>